### ISSUE TITLE
Adopters of this repo, or the RFC approach for org-internal decision making in general?

### ISSUE THREAD

**Issue by spier** [LeadSV/rfc#3]
Hi @jakobo and @kubukoz. 

Thank you for sharing this project! ❤️ 

Do you know of organizations that have used your repo?
Or even more general, orgs that have adopted the RFC approach internally, no matter how they did it.

I am asking because we have collected an InnerSource pattern here, that describes this idea as well.
It contains a list of adopters already, and it would be great to add more:
https://patterns.innersourcecommons.org/p/transparent-cross-team-decision-making-using-rfcs

Btw I noticed that this repo is already around for a while, so maybe my chances of a getting a response are small, but I figured that it doesn't hurt to try.

**Comment by thecodedrift** [comment]
Appreciate the note. While there are other companies I know that use RFCs in a process similar to what we have here in this repository, it's not really my place to share them. However, the [forks list](https://github.com/jakobo/rfc/forks?include=active%2Carchived%2Cinactive%2Cnetwork&page=1&period=&sort_by=last_updated) for this repository is probably a good starting point.

To avoid spamming Kobukoz (they just helped with some initial typos), I'm going to close this for now but do appreciate you writing up such great notes about the RFC process.

**Comment by spier** [comment]
Thank you for the feedback @jakobo! Will start with the forks list as suggested.

I will also add your repo as a reference to our pattern, as it might help some people as a starting point to implement their own company-internal RFC process.

**Comment by spier** [comment]
Just FYI
https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/667/files#diff-1c384a3190927e99297d777d65985c43548734bbffa18f6bcf396a9b3c3f17acR64
